### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'pykalman==0.9.5' distribution was not found and is required by sleap

### ISSUE THREAD

**Issue by monajalal** [murthylab/sleap#384]
After installing from repo following these instructions I got the following error

```
(sleap_env) mona@mona:~/research/animal_pose/sleap/sleap$ pip install --no-deps -e .
Obtaining file:///home/mona/research/animal_pose/sleap/sleap
Installing collected packages: sleap
  Running setup.py develop for sleap
Successfully installed sleap
(sleap_env) mona@mona:~/research/animal_pose/sleap/sleap$ sleap-label
Traceback (most recent call last):
  File "/home/mona/anaconda3/envs/sleap_env/bin/sleap-label", line 33, in <module>
    sys.exit(load_entry_point('sleap', 'console_scripts', 'sleap-label')())
  File "/home/mona/anaconda3/envs/sleap_env/bin/sleap-label", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mona/research/animal_pose/sleap/sleap/sleap/__init__.py", line 8, in <module>
    from sleap.io.dataset import Labels
  File "/home/mona/research/animal_pose/sleap/sleap/sleap/io/dataset.py", line 50, in <module>
    from sleap.instance import (
  File "/home/mona/research/animal_pose/sleap/sleap/sleap/instance.py", line 31, in <module>
    from sleap.io.video import Video
  File "/home/mona/research/animal_pose/sleap/sleap/sleap/io/video.py", line 17, in <module>
    from sleap.util import json_loads, json_dumps
  File "/home/mona/research/animal_pose/sleap/sleap/sleap/util.py", line 13, in <module>
    from pkg_resources import Requirement, resource_filename
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3256, in <module>
    @_call_aside
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pykalman==0.9.5' distribution was not found and is required by sleap

```

Commands:

```
486  mkdir sleap
  487  cd sleap/
  488  conda create -n sleap_env python=3.6 -y
  489  conda activate sleap_env
  490  pip install sleap==1.0
  491  history
  492  sleap-label
  493  pip uninstall sleap==1.0
  494  history
  495  git clone https://github.com/murthylab/sleap.git
  496  pip install -r dev_requirements.txt
  497  ls
  498  cd sleap/
  499  pip install -r dev_requirements.txt
  500  pip install --no-deps -e .
  501  sleap-label

```

**Comment by monajalal** [comment]
basically exact version of pykalman and scipy should also be added to requirements.txt 
pykalman==0.9.5
and
scipy==1.4.1
```
(sleap_env) mona@mona:~/research/animal_pose/sleap/sleap$ pip install pykalman==0.9.5
Collecting pykalman==0.9.5
  Downloading pykalman-0.9.5.tar.gz (228 kB)
     |████████████████████████████████| 228 kB 2.2 MB/s 
Building wheels for collected packages: pykalman
  Building wheel for pykalman (setup.py) ... done
  Created wheel for pykalman: filename=pykalman-0.9.5-py3-none-any.whl size=48462 sha256=d839fcdb62b1e8cc7662a8a016532d539713fb642e85ed3aa590295b1d43b17b
  Stored in directory: /home/mona/.cache/pip/wheels/18/44/0f/af97d6da14881ab826a241f8238f21a9fcd68b260fd8ab7fc3
Successfully built pykalman
ERROR: sleap 1.0.8 has requirement scipy<=1.4.1, but you'll have scipy 1.5.1 which is incompatible.
Installing collected packages: pykalman
Successfully installed pykalman-0.9.5
(sleap_env) mona@mona:~/research/animal_pose/sleap/sleap$ pip uninstall scipy
Found existing installation: scipy 1.5.1
Uninstalling scipy-1.5.1:
  Would remove:
    /home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/scipy-1.5.1.dist-info/*
    /home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/scipy.libs/libgfortran-ed201abd.so.3.0.0
    /home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/scipy.libs/libopenblasp-r0-085ca80a.3.9.so
    /home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages/scipy/*
Proceed (y/n)? y
  Successfully uninstalled scipy-1.5.1

(sleap_env) mona@mona:~/research/animal_pose/sleap/sleap$ pip install scipy==1.4.1
Collecting scipy==1.4.1
  Downloading scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (26.1 MB)
     |████████████████████████████████| 26.1 MB 31 kB/s 
Requirement already satisfied: numpy>=1.13.3 in /home/mona/anaconda3/envs/sleap_env/lib/python3.6/site-packages (from scipy==1.4.1) (1.19.1)
Installing collected packages: scipy
Successfully installed scipy-1.4.1
(sleap_env) mona@mona:~/research/animal_pose/sleap/sleap$ sleap-label
2020-07-21 18:24:36.645111: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-07-21 18:24:36.645196: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-07-21 18:24:36.645204: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.


```

**Comment by ntabris** [comment]
Hi, @monajalal. As far as I can tell we do have `pykalman` and `scipy` in `requirements.txt`. Maybe you didn't `pip install -r requirements.txt`?

**Comment by monajalal** [comment]
@ntabris I actually did as shown in   499  pip install -r dev_requirements.txt

**Comment by ntabris** [comment]
Those are the requirements for developers (e.g., unit testing, linter). You also need `requirements.txt`.

If you're still having problems, I'd suggest creating a new virtual environment w/ Python 3.6 (using conda, venv, or whatever you prefer) and just doing a `pip install sleap` to install sleap into that.

**Comment by monajalal** [comment]
@ntabris well, I am interested in the dev version not version 1.0.0, hence that's why I followed the instruction for installing the dev version

![sleap](https://user-images.githubusercontent.com/1892917/88117819-2121a580-cb8a-11ea-83f5-78a49ed7aee5.png)

here it doesn't say anything about requirements.txt

I think you should also add that to the instruction set as in the screenshot (even though I was able to figure it on my own but it would help others I'd say IMHO).

**Comment by ntabris** [comment]
Thanks for the suggestion! We should probably clarify the dev installation instructions. In the instructions you copied, the relevant packages are installed when you create the conda env (it's using `environment.yml` rather than `requirements.txt`).

Regardless, happy to hear you got things working!
