### ISSUE TITLE
ZMQ Error

### ISSUE THREAD

**Issue by MattKDawson** [murthylab/sleap#417]
Hi!

I am installing SLEAP on a lab computer to make use of more GPU memory; however, when trying to run training on the new SLEAP installation, I get this error:

(sleap_env) C:\Users\matth>sleap-label
2020-11-02 22:04:51.135937: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
c:\users\matth\anaconda3\envs\sleap_env\lib\site-packages\shiboken2\files.dir\shibokensupport\signature\parser.py:97: FutureWarning: split() requires a non-empty pattern match.
  return [x.strip() for x in split(argstr) if x.strip() not in ("", ",")]
QWindowsWindow::setGeometry: Unable to set geometry 1920x1017+0+29 (frame: 1938x1064-9-9) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1001+0+29 (frame: 1938x1048-9-9) margins: 9, 38, 9, 9 minimum size: 532x1017 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=550,1064 maxtrack=0,0)
Traceback (most recent call last):
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\learning\dialog.py", line 559, in run
    items_for_inference=items_for_inference,
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\learning\runners.py", line 393, in run_learning_pipeline
    save_viz=save_viz,
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\learning\runners.py", line 440, in run_gui_training
    win = LossViewer()
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\nn\monitor.py", line 38, in __init__
    self.setup_zmq(zmq_context)
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\nn\monitor.py", line 231, in setup_zmq
    self.sub.bind("tcp://127.0.0.1:9001")
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Permission denied

Any help you can provide is greatly appreciated! :)

**Comment by talmo** [comment]
Hi @MattKDawson,

That's a weird issue! Do you mind sharing a couple of pieces of diagnostic info?

First, open up a Powershell console as an administrator:
![image](https://user-images.githubusercontent.com/3187454/98007098-fb2eb280-1dc0-11eb-9d14-35499be9d59e.png)

Then, run the following commands and paste the outputs here:

1. What Windows version are you on?
`[System.Environment]::OSVersion.Version`

2. Do you have Hyper-V enabled?
`Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V`

3. Do you have any reserved ports?
`netsh int ipv4 show excludedportrange protocol=tcp`


Thanks!

**Comment by MattKDawson** [comment]
Hi @talmo !

Here are the outputs in the order you requested them :)

1. PS C:\WINDOWS\system32> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19042  0

2. PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V


FeatureName      : Microsoft-Hyper-V
DisplayName      : Hyper-V Platform
Description      : Provides the services that you can use to create and manage virtual machines and their resources.
RestartRequired  : Possible
State            : Disabled
CustomProperties :

3. PS C:\WINDOWS\system32> netsh int ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      9001        9001

* - Administered port exclusions.

I enabled Hyper-V and attempted running training again in SLEAP, and again received the following error readout in my Anaconda terminal:

c:\users\matth\anaconda3\envs\sleap_env\lib\site-packages\shiboken2\files.dir\shibokensupport\signature\parser.py:97: FutureWarning: split() requires a non-empty pattern match.
  return [x.strip() for x in split(argstr) if x.strip() not in ("", ",")]
QWindowsWindow::setGeometry: Unable to set geometry 1920x1017+0+29 (frame: 1938x1064-9-9) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1001+0+29 (frame: 1938x1048-9-9) margins: 9, 38, 9, 9 minimum size: 532x1017 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=550,1064 maxtrack=0,0)
Traceback (most recent call last):
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\learning\dialog.py", line 559, in run
    items_for_inference=items_for_inference,
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\learning\runners.py", line 393, in run_learning_pipeline
    save_viz=save_viz,
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\learning\runners.py", line 440, in run_gui_training
    win = LossViewer()
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\nn\monitor.py", line 38, in __init__
    self.setup_zmq(zmq_context)
  File "C:\Users\matth\Anaconda3\envs\sleap_env\lib\site-packages\sleap\nn\monitor.py", line 231, in setup_zmq
    self.sub.bind("tcp://127.0.0.1:9001")
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Permission denied

**Comment by talmo** [comment]
Hi @MattKDawson,

You definitely don't need Hyper-V enabled -- I just wanted to check since it can sometimes block some ranges of TCP ports necessary for communication during training.

So the issue does seem to be that your port 9001 is blocked, which unfortunately is the port we use in SLEAP. There's a bunch of things that could be using it, but one common culprit seems to be some Intel driver app which you can disable like this:

1. Start menu
2. Type: Services
3. Find the service called: Intel(R) Graphics Command Center Service
4. Right-click > Properties > Startup type = Disabled
5. Restart

If you don't see that service you can try just manually deleting that port exclusion like this:
`netsh int ip delete excludedportrange protocol=tcp numberofports=2 startport=9000`
But you might get a Permission denied error if the program is still running.

Try the Intel one first though and let me know if it's still giving you an error and we'll go from there.

**Comment by MattKDawson** [comment]
Hi @talmo !

That seems to have fixed it! Thank you so much for your help, I really appreciate it and I know the rest of my lab does too :)

I hope you enjoy the rest of your day!

**Comment by talmo** [comment]
Great! I'll close this but feel free to let me know if you run into any other issues! Cheers :)
