### ISSUE TITLE
Inference step crashes:     model_config = json.loads(model_config.decode('utf-8'))

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#427]
Hello

I ran for 25 epochs (and stopped the running early). When I tried to predict, I got this weird crash, seems something is not coded right? Not sure.
 
```

Run Path: /home/cat/models/201208_082211.multi_instance.10
Finished training multi_instance.
Command line call:
sleap-track \
--labels \
/home/cat/gerbil.slp \
--only-suggested-frames \
-m \
/home/cat/models/201208_082211.multi_instance.10 \
-o \
/home/cat/predictions/gerbil.slp.201208_085022.predictions.slp

2020-12-08 08:50:23.923048: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-12-08 08:50:23.924370: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Namespace(cpu=False, first_gpu=False, frames=None, gpu=0, labels='/home/cat/gerbil.slp', last_gpu=False, models=['/home/cat/models/201208_082211.multi_instance.10'], only_labeled_frames=False, only_suggested_frames=True, output='/home/cat/predictions/gerbil.slp.201208_085022.predictions.slp', test_pipeline=False, video_path='', **{'bottomup.peak_threshold': None, 'single.peak_threshold': None, 'topdown.batch_size': None, 'topdown.peak_threshold': None, 'tracking.clean_instance_count': None, 'tracking.clean_iou_threshold': None, 'tracking.img_scale': None, 'tracking.kf_init_frame_count': None, 'tracking.kf_node_indices': None, 'tracking.match': None, 'tracking.min_match_points': None, 'tracking.min_new_track_points': None, 'tracking.of_max_levels': None, 'tracking.of_window_size': None, 'tracking.post_connect_single_breaks': None, 'tracking.pre_cull_iou_threshold': None, 'tracking.pre_cull_to_target': None, 'tracking.similarity': None, 'tracking.target_instance_count': None, 'tracking.track_window': None, 'tracking.tracker': None, 'video.dataset': '', 'video.input_format': ''})
2020-12-08 08:50:24.703781: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-12-08 08:50:24.736848: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-08 08:50:24.737078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 with Max-Q Design computeCapability: 7.5
coreClock: 1.155GHz coreCount: 14 deviceMemorySize: 3.82GiB deviceMemoryBandwidth: 149.04GiB/s
2020-12-08 08:50:24.737112: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-12-08 08:50:24.737150: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-12-08 08:50:24.738040: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-12-08 08:50:24.738270: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-12-08 08:50:24.739646: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-12-08 08:50:24.740396: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-12-08 08:50:24.740440: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-12-08 08:50:24.740535: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-08 08:50:24.740813: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-12-08 08:50:24.740997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
Traceback (most recent call last):
  File "/home/cat/anaconda3/envs/sleap_env/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/nn/inference.py", line 1276, in main
    model_paths_by_head, labels_path=args.labels, policy_args=policy_args
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/nn/inference.py", line 1189, in make_predictor_from_models
    trained_model_paths["multi_instance"], **get_relevant_args("bottomup")
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/sleap/nn/inference.py", line 683, in from_trained_models
    bottomup_keras_model_path, compile=False
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/cat/anaconda3/envs/sleap_env/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
Process return code: 1

```

**Comment by talmo** [comment]
Hi @catubc,

Yes, this is an issue with TensorFlow -- since they didn't version fence the h5py dependency, new installs will pull down h5py>2.10.0 which breaks Keras model loading support.

You can fix this by either installing the pre-release of the next version of SLEAP ([v1.0.10a9](https://github.com/murthylab/sleap/releases/tag/v1.0.10a9)) or simply by `pip install h5py==2.10.0`.

Cheers!
