### ISSUE TITLE
sleap-track error "ValueError: Unable to run inference with ['centered_instance'] heads."

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#430]
Hi
I have a trained model and trying to predict on a video.
Am getting this mystery error, I tried different .json files as well.
Any advice?
Thanks

```

(sleap_env2) cat@cat-work:~$ sleap-track "/home/cat/Downloads/sleap_video.mp4" -m "/home/cat/Downloads/sleap/models/201208_111035.centered_instance.60/training_config.json" -o "/home/cat/Downloads/sleap_video.mp4.slp"
2020-12-08 13:14:04.470938: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-12-08 13:14:04.472414: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Namespace(cpu=False, first_gpu=False, frames=None, gpu=0, labels=None, last_gpu=False, models=['/home/cat/Downloads/sleap/models/201208_111035.centered_instance.60/training_config.json'], only_labeled_frames=False, only_suggested_frames=False, output='/home/cat/Downloads/sleap_video.mp4.slp', test_pipeline=False, video_path='/home/cat/Downloads/sleap_video.mp4', **{'bottomup.peak_threshold': None, 'single.peak_threshold': None, 'topdown.batch_size': None, 'topdown.peak_threshold': None, 'tracking.clean_instance_count': None, 'tracking.clean_iou_threshold': None, 'tracking.img_scale': None, 'tracking.kf_init_frame_count': None, 'tracking.kf_node_indices': None, 'tracking.match': None, 'tracking.min_match_points': None, 'tracking.min_new_track_points': None, 'tracking.of_max_levels': None, 'tracking.of_window_size': None, 'tracking.post_connect_single_breaks': None, 'tracking.pre_cull_iou_threshold': None, 'tracking.pre_cull_to_target': None, 'tracking.similarity': None, 'tracking.target_instance_count': None, 'tracking.track_window': None, 'tracking.tracker': None, 'video.dataset': '', 'video.input_format': ''})
2020-12-08 13:14:05.491717: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-12-08 13:14:05.521601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-12-08 13:14:05.521885: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-12-08 13:14:05.521981: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-12-08 13:14:05.523415: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-12-08 13:14:05.523717: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-12-08 13:14:05.525487: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-12-08 13:14:05.526478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-12-08 13:14:05.526543: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-12-08 13:14:05.527880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
Traceback (most recent call last):
  File "/home/cat/anaconda3/envs/sleap_env2/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/inference.py", line 1276, in main
    model_paths_by_head, labels_path=args.labels, policy_args=policy_args
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/inference.py", line 1208, in make_predictor_from_models
    f"Unable to run inference with {list(trained_model_paths.keys())} heads."
ValueError: Unable to run inference with ['centered_instance'] heads.
(sleap_env2) cat@cat-work:~$ 
```

**Comment by talmo** [comment]
Hi @catubc,

For top-down inference, you must have both a centroids and centered instance model.

If you trained through the GUI, it likely went through and trained both models in sequence.

You can specify both models in the command line like this:

```
sleap-track "video.mp4" -m "path/to/centered_instance_model" -m "path/to/centroid_model" -o "video.mp4.slp"
```

See this page for more info: https://sleap.ai/guides/choosing-models.html#choosing-models

Closing but feel free to re-open if you're still having issues after specifying the centroid model.

Cheers,

Talmo
