### ISSUE TITLE
Hungarian Algorithm: ValueError: cost matrix is infeasible

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#441]
Hello
i'm trying to run a prediction step using tracker params and I'm getting a weird error. It seems to be related to the hungarian algorithm parameters (Sleap seems to run ok without that CLI option).

Here's the crash log.

```
(sleap_env2) cat@cat-work:/mnt/adfe6e7b-b77b-4731-bc9e-e639667faba4/madeline/march_2/march_16$ sleap-track -m "/mnt/adfe6e7b-b77b-4731-bc9e-e639667faba4/dan/sleap/cohort1/models-20201217T070218Z-001/models/201215_075126.centered_instance.1597" -m "/mnt/adfe6e7b-b77b-4731-bc9e-e639667faba4/dan/sleap/cohort1/models-20201217T070218Z-001/models/201215_131240.centroid.1597" --tracking.tracker simple --tracking.track_window 4 --tracking.match hungarian "/mnt/adfe6e7b-b77b-4731-bc9e-e639667faba4/madeline/march_2/march_16/2020-3-16_01_54_23_358257_compressed/2020-3-16_01_54_23_358257_compressed.avi"

2021-01-03 04:35:22.337652: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Namespace(cpu=False, first_gpu=False, frames=None, gpu=0, labels=None, last_gpu=False, models=['/mnt/adfe6e7b-b77b-4731-bc9e-e639667faba4/dan/sleap/cohort1/models-20201217T070218Z-001/models/201215_075126.centered_instance.1597', '/mnt/adfe6e7b-b77b-4731-bc9e-e639667faba4/dan/sleap/cohort1/models-20201217T070218Z-001/models/201215_131240.centroid.1597'], only_labeled_frames=False, only_suggested_frames=False, output=None, test_pipeline=False, video_path='/mnt/adfe6e7b-b77b-4731-bc9e-e639667faba4/madeline/march_2/march_16/2020-3-16_01_54_23_358257_compressed/2020-3-16_01_54_23_358257_compressed.avi', **{'bottomup.batch_size': 4, 'bottomup.peak_threshold': None, 'single.batch_size': 4, 'single.peak_threshold': None, 'topdown.batch_size': 4, 'topdown.peak_threshold': None, 'tracking.clean_instance_count': None, 'tracking.clean_iou_threshold': None, 'tracking.img_scale': None, 'tracking.kf_init_frame_count': None, 'tracking.kf_node_indices': None, 'tracking.match': 'hungarian', 'tracking.min_match_points': None, 'tracking.min_new_track_points': None, 'tracking.of_max_levels': None, 'tracking.of_window_size': None, 'tracking.post_connect_single_breaks': None, 'tracking.pre_cull_iou_threshold': None, 'tracking.pre_cull_to_target': None, 'tracking.similarity': None, 'tracking.target_instance_count': None, 'tracking.track_window': 4, 'tracking.tracker': 'simple', 'video.dataset': '', 'video.input_format': ''})
2021-01-03 04:35:23.921876: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-01-03 04:35:23.950979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2021-01-03 04:35:23.951032: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-03 04:35:23.955011: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-03 04:35:23.957455: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-01-03 04:35:23.959537: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-01-03 04:35:23.964264: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-01-03 04:35:23.965773: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-01-03 04:35:23.971108: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-03 04:35:23.972408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
2021-01-03 04:35:24.367830: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3391945000 Hz
2021-01-03 04:35:24.370100: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5647aa7e3fe0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-01-03 04:35:24.370126: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-01-03 04:35:24.470730: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5647aa7863c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-01-03 04:35:24.470767: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2021-01-03 04:35:24.471650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2021-01-03 04:35:24.471739: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-03 04:35:24.471790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-03 04:35:24.471832: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-01-03 04:35:24.471873: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-01-03 04:35:24.471915: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-01-03 04:35:24.471976: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-01-03 04:35:24.472029: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-03 04:35:24.473296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-01-03 04:35:24.473355: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-03 04:35:24.893949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-03 04:35:24.893993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2021-01-03 04:35:24.894003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2021-01-03 04:35:24.895557: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10598 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
2021-01-03 04:35:38.985336: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-03 04:35:39.764286: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-03 04:36:01.714518: W tensorflow/core/common_runtime/bfc_allocator.cc:312] Garbage collection: deallocate free memory regions (i.e., allocations) so that we can re-allocate a larger region to avoid OOM due to memory fragmentation. If you see this message frequently, you are running near the threshold of the available device memory and re-allocation may incur great performance overhead. You may try smaller batch sizes to observe the performance impact. Set TF_ENABLE_GPU_GARBAGE_COLLECTION=false if you'd like to disable this feature.
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py:38: RuntimeWarning: invalid value encountered in true_divide
  similarity = np.nansum(np.exp(-dists)) / np.sum(ref_visible)
Traceback (most recent call last):
  File "/home/cat/anaconda3/envs/sleap_env2/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/inference.py", line 2416, in main
    video_predicted_frames = predictor.predict(video_reader, make_labels=False, make_instances=True)
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/inference.py", line 1331, in predict
    lfs = self.make_labeled_frames_from_generator(generator, data_provider)
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/inference.py", line 1301, in make_labeled_frames_from_generator
    untracked_instances=predicted_instances, img=image, t=frame_ind
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracking.py", line 431, in track
    matching_function=self.matching_function,
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py", line 455, in from_candidate_instances
    cost, untracked_instances, candidate_tracks, matching_function
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py", line 470, in from_cost_matrix
    match_inds = matching_function(cost_matrix)
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/sleap/nn/tracker/components.py", line 84, in hungarian_matching
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
  File "/home/cat/anaconda3/envs/sleap_env2/lib/python3.6/site-packages/scipy/optimize/_lsap.py", line 104, in linear_sum_assignment
    b = _lsap_module.calculate_assignment(cost_matrix)
ValueError: cost matrix is infeasible
```

**Comment by talmo** [comment]
Hi @catubc,

Strange, this probably shouldn't happen if there are no visible nodes but I'm guessing there's a special case somewhere. For now, try switching the matching to `greedy` instead of `hungarian`.

I'll tag this as a bug so we can track it down for the next version. Thanks!

Talmo

**Comment by catubc** [comment]
Ok thanks.  What happens if the matching is not specified?  Is there no matching done at all, or some default method?

**Comment by talmo** [comment]
I believe it defaults to greedy matching.

**Comment by catubc** [comment]
Ok great, thanks for letting me know (I just ran 10 1hr movies overnight lol).

btw: must be superlate on your end, get some sleep!

**Comment by talmo** [comment]
No sleep -- only SLEAP! ;)

I'm actually going to keep this open so we have a reminder to dig into the Hungarian matching issue.
