### ISSUE TITLE
Faster conversion from .slp to .csv (plus lower memory + parallelization)

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#443]
Hi 
I am finding that conversion from .slp to .csv is taking about 1.5 times realtime of the video.  I assume there's a much faster way to port .slp tracks.

That would be ok if i could parallelize the conversion, but it seems there are very large arrays reserved by this step. For a single 1hr video with 4-6 animals, up to 14 features each there are 100GB Ram arrays requested - even though the final .h5 file  saved is about 200MB.

I can also help with these issues via a separate PR - just need to know where code is and what you suggest.

Here is my conversion function based on what you provided a while ago:

```

def convert_slp(fname_slp):
   
    fname_h5 = fname_slp[:-4]+'.analysis.h5'
    if os.path.exists(fname_h5)==False:
        text = 'sleap-convert --format analysis ' + fname_slp # "/home/cat/Downloads/sleap_video.mp4.tracker_flow.slp"
        print ("Converting to .h5: ", text)
        os.system(text)
    
    fname_csv = fname_slp[:-4]+'.analysis.csv'
    if os.path.exists(fname_csv)==False:
        print ("")
        print ("... converting h5 to csv")
        # Open the HDF5 file using h5py.
        with h5py.File(fname_h5, "r") as f:

          # Print a list of the keys available.
          print("Keys in the HDF5 file:", list(f.keys()))

          # Load all the datasets into a dictionary.
          data = {k: v[:] for k, v in f.items()}

          # Here we're just converting string arrays into regular Python strings.
          data["node_names"] = [s.decode() for s in data["node_names"].tolist()]
          data["track_names"] = [s.decode() for s in data["track_names"].tolist()]

          # And we just flip the order of the tracks axes for convenience.
          data["tracks"] = np.transpose(data["tracks"])

          # And finally convert the data type of the track occupancy array to boolean.
          # We'll see what this array is used for further down.
          data["track_occupancy"] = data["track_occupancy"].astype(bool)

        # Describe the values in the data dictionary we just created.
        for key, value in data.items():
          if isinstance(value, np.ndarray):
            print(f"{key}: {value.dtype} array of shape {value.shape}")
          else:
            print(f"{key}: {value}")
    
        # Get valid frame IDs
        valid_frame_idxs = np.argwhere(data["track_occupancy"].any(axis=1)).flatten()

        # Get tracks
        tracks = []
        for frame_idx in tqdm(valid_frame_idxs):
          # Get the tracking data for the current frame.
          frame_tracks = data["tracks"][frame_idx]

          # Loop over the animals in the current frame.
          for i in range(frame_tracks.shape[-1]):
            pts = frame_tracks[..., i]
            
            if np.isnan(pts).all():
              # Skip this animal if all of its points are missing (i.e., it wasn't
              # detected in the current frame).
              continue
            
            # Let's initialize our row with some metadata.
            detection = {"track": data["track_names"][i], "frame_idx": frame_idx}

            # Now let's fill in the coordinates for each body part.
            for node_name, (x, y) in zip(data["node_names"], pts):
              detection[f"{node_name}.x"] = x
              detection[f"{node_name}.y"] = y

            # Add the row to the list and move on to the next detection.
            tracks.append(detection)

        # Once we're done, we can convert this list of rows into a table using Pandas.
        tracks = pd.DataFrame(tracks)

        print(tracks.head())
    
        tracks.to_csv(fname_csv, index=False)

    # final step convert to .npy file
    fname_npy = fname_slp[:-4]+'.analysis.npy'
    if os.path.exists(fname_npy)==False:
        # csv loader to .npy
        traces =[]
        with open(fname_csv, mode='r') as infile:
            reader = csv.reader(infile)
            for row in reader:
                traces.append(row)
        
        traces.pop(0)
        
        np.save(fname_npy, traces)

```

Here's the memory crash log for the run:

```
(sleap_dev) cat@cat-Precision-T3610:~$ sleap-convert --format analysis /media/cat/7e3d5af3-7d7b-424d-bdd5-eb995a4a0c62/dan/cohort1/march_16/2020-3-16_06_55_40_714236_compressed/2020-3-16_06_55_40_714236_compressed.avi.predictions.slp
2021-01-04 10:03:00.317797: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2021-01-04 10:03:00.319733: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Traceback (most recent call last):
  File "/home/cat/miniconda3/envs/sleap_dev/bin/sleap-convert", line 33, in <module>
    sys.exit(load_entry_point('sleap', 'console_scripts', 'sleap-convert')())
  File "/home/cat/code/sleap/sleap/io/convert.py", line 95, in main
    write_analysis(labels, output_path=output_path, all_frames=True)
  File "/home/cat/code/sleap/sleap/info/write_tracking_h5.py", line 192, in main
    labels, all_frames
  File "/home/cat/code/sleap/sleap/info/write_tracking_h5.py", line 77, in get_occupancy_and_points_matrices
    (frame_count, node_count, 2, track_count), np.nan, dtype=float
  File "/home/cat/miniconda3/envs/sleap_dev/lib/python3.6/site-packages/numpy/core/numeric.py", line 325, in full
    a = empty(shape, dtype, order)
MemoryError: Unable to allocate 97.8 GiB for an array with shape (89988, 14, 2, 5208) and data type float64
(sleap_dev) cat@cat-Precision-T3610:~$ 
```

**Comment by talmo** [comment]
Definitely happy to accept a PR -- here's the relevant submodule:
https://github.com/murthylab/sleap/blob/master/sleap/info/write_tracking_h5.py

The new approach would likely require some refactoring in order to loop through chunks of frames. The easiest would be to add a frame index range selector to the CLI and main processing function and then run sleap-convert in parts.

There's also plenty of room for optimization in that code, including using sparse matrices/RLE for occupancy and float32 dtypes where possible.
