### ISSUE TITLE
GUI unresponsive when editing predictions

### ISSUE THREAD

**Issue by jens-k** [murthylab/sleap#444]
I predicted all frames of a large video (~2 hours, ~2GB) and merged the result to my SLEAP project. I am now editing some of the predictions to improve my model. However, when double clicking on the yellow predictions, the GUI becomes unresponsive for around 20-30 sec (Windows also marks it unresponsive). This makes the process quite time-consuming.

Interestingly, CPU, RAM or HDD do **not** substantially go up during that non-responsive time.

The problem did not occur when I only had a few dozen frames predicted in the same video. 
I run SLEAP 1.0.10 on a Windows 10 computer.

Any suggestions for dealing with this issue?

**Comment by talmo** [comment]
Hey @jens-k,

Odd that the resources don't go up while it's frozen. Do you mind providing some more info?

- What OS are you on?
- How many instances (user labeled/predicted) are in the labels?
- How many instances do you have per frame?
- How many nodes are in the skeleton?
- How many videos are in the labels?

Alternatively, do you mind sharing the .slp file?

Cheers,

Talmo

**Comment by jens-k** [comment]
Hey @talmo ,
thanks for answering that quickly! 

- Windows 10
- This particular video has 68 labelled and around 200k (= all) predicted frames.
- only 1 instance per frame (it's all only one animal, non-human primate)
- one skeleton in the entire project, 7 nodes (2 feet, pelvis, 2 hands, neck, head) 
- The project has 4 videos, each has around 200k frames (I added predictions only for one video yet). 

This is only one recording night, many more are to come. So if this is a bottleneck, should I very much downsample my videos before labelling/predicting them? I could do that by a factor of 10 (= 3 frames per second) max, going further than that would be tough. Would lower resolution help (currently 1280x1024)?

Thanks and all the best,
Jens

**Comment by talmo** [comment]
Aha, I see -- right so we routinely work with multi-instance 250k+ frame videos but typically all we do is correct the track identity of individual frames rather than create new user instances. I'm assuming this is the problem here.

Typically what we do when we're building an initial labeling dataset for training models is to create a project with several videos, [generate suggestions](https://sleap.ai/tutorials/initial-labeling.html#initial-labeling) for labeling and then just run the inference on those frames (<2k frames). You can then just focus on this smaller subset rather than running SLEAP on the entire long video before you have a solid model.

Here's my suggestion:

1. Save your labels project to a new .slp file and delete all of the predictions.
2. If you can, add more videos to the project (but not necessary if you plan on adding more later or training individual models for each session).
3. Generate suggested frames for labeling (~500 to 1000), either using image features or random frames. If the image changes gradually over the length of the session, strided sampling may be better.
4. Run inference on the suggestions only.
5. Correct the predictions and retrain until you're happy with the model.

Let me know if you have any questions or run into any issues!

Talmo

**Comment by jens-k** [comment]
Hey Talmo, thanks for your help!

I got up to point 4 but then got stuck. Until now, I have run inference only on entire videos, where I can get away with a call like:
sleap-track ~/video.mp4 -m ~/201228_122201.single_instance/training_config.json --tracking.tracker none -o ~/video.mp4.predictions.slp

If I only want suggested frames to be predicted, I guess I need to call sleap-track on a package containing the actual images. So I tried doing that with an exportet "Training Package":
sleap-track --labels ~/package.pkg.slp --only-suggested-frames -m ~/201228_122201.single_instance/training_config.json --tracking.tracker none -o ~/package.pkg.slp.predictions.slp

It seems inference is being performed (the project contains 10 videos) but then an error occurs that I don't understand:

```
INFO:sleap.nn.inference:Finished 50 examples in 3.07 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 16.311929308584556
INFO:sleap.nn.inference:Finished 50 examples in 0.77 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 64.86491167783807
INFO:sleap.nn.inference:Finished 50 examples in 0.76 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 65.94993891346152
INFO:sleap.nn.inference:Finished 50 examples in 0.76 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 65.99279387006939
INFO:sleap.nn.inference:Finished 50 examples in 0.90 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 55.7215241668283
INFO:sleap.nn.inference:Finished 50 examples in 0.77 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 64.52273099970986
INFO:sleap.nn.inference:Finished 50 examples in 0.77 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 64.69488561835438
INFO:sleap.nn.inference:Finished 50 examples in 0.78 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 64.41800538590101
INFO:sleap.nn.inference:Finished 50 examples in 0.76 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 65.75362394725794
INFO:sleap.nn.inference:Finished 50 examples in 0.77 seconds (inference + postprocessing)
INFO:sleap.nn.inference:examples/s = 64.5672093777921
Traceback (most recent call last):
  File "/home/klinzing/.conda/envs/sleap/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 1309, in main
    video_predicted_frames = predictor.predict(video_reader)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 961, in predict
    generator = self.predict_generator(data_provider)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 949, in predict_generator
    return safely_generate(self.pipeline.make_dataset())
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/pipelines.py", line 270, in make_dataset
    ds = self.providers[0].make_dataset()
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/providers.py", line 280, in make_dataset
    test_image = tf.convert_to_tensor(self.video.test_frame)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/io/video.py", line 964, in __getattr__
    return getattr(self.backend, item)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/io/video.py", line 164, in test_frame
    self._test_frame_ = self.get_frame(self.last_frame_idx)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/io/video.py", line 319, in get_frame
    frame = self.__dataset_h5[idx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/h5py/_hl/selections.py", line 466, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/h5py/_hl/selections.py", line 486, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (-1) out of range (0--1)
```
Does it try to access the actual video (video.py, line 319)? If so, I think there is no way of knowing where they are on the remote server (I run inference on tigergpu).

**Comment by jens-k** [comment]
Should I provide several videos via --video.dataset? Why does sleap need to access the videos at that point?

**Comment by jens-k** [comment]
Thanks! Now I get another error though. Something about RGB vs grayscale? My videos should be the latter (I selected that during import).

```
Traceback (most recent call last):
  File "/home/klinzing/.conda/envs/sleap/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 1309, in main
    video_predicted_frames = predictor.predict(video_reader)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 961, in predict
    generator = self.predict_generator(data_provider)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 949, in predict_generator
    return safely_generate(self.pipeline.make_dataset())
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/pipelines.py", line 275, in make_dataset
    ds = transformer.transform_dataset(ds)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/normalization.py", line 372, in transform_dataset
    normalize, num_parallel_calls=tf.data.experimental.AUTOTUNE
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1591, in map
    self, map_func, num_parallel_calls, preserve_cardinality=True)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3926, in __init__
    use_legacy_function=use_legacy_function)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3147, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2395, in _get_concrete_function_internal
    *args, **kwargs)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3140, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3082, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/normalization.py:354 normalize  *
        example[self.image_key] = ensure_grayscale(example[self.image_key])
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/normalization.py:97 ensure_grayscale  *
        return tf.image.rgb_to_grayscale(image)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/ops/image_ops_impl.py:1884 rgb_to_grayscale
        gray_float = math_ops.tensordot(flt_image, rgb_weights, [-1, -1])
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/ops/math_ops.py:4106 tensordot
        ab_matmul = matmul(a_reshape, b_reshape)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/ops/math_ops.py:2798 matmul
        a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_math_ops.py:5626 mat_mul
        name=name)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py:742 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py:595 _create_op_internal
        compute_device)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:3322 _create_op_internal
        op_def=op_def)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1786 __init__
        control_input_ops)
    /home/klinzing/.conda/envs/sleap/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1622 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 1 and 3 for 'rgb_to_grayscale/Tensordot/MatMul' (op: 'MatMul') with input shapes: [1310720,1], [3,1].

```

**Comment by talmo** [comment]
Hey @jens-k,

Sorry, I forgot to reply to this thread:

Nope, you're doing everything correctly. Found the issue and working on a patch which I'll have ready in a pre-release in the next couple of days.

If you want to try it out sooner, follow these steps:

1. Install SLEAP v1.1.0a8 following [the instructions here](https://github.com/murthylab/sleap/releases/tag/v1.1.0a8).
2. Upgrade to the hotfix version:
```
pip install https://github.com/murthylab/sleap/archive/talmo/inference_cli.zip
```

Let me know if you do update following the instructions above and are still having issues.

I'll update this issue when I'm finished with the complete patch.

Cheers!

Talmo

**Comment by jens-k** [comment]
Thanks @talmo 
I followed the instructions and installed the hotfix. Now I get the following:

```
2021-01-16 11:10:21.947856: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-16 11:10:24.028251: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-01-16 11:10:24.052312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2021-01-16 11:10:24.052628: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-01-16 11:10:24.054998: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-01-16 11:10:24.057353: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-01-16 11:10:24.057847: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-01-16 11:10:24.060443: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-01-16 11:10:24.061756: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-01-16 11:10:24.066572: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-01-16 11:10:24.069546: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
Namespace(cpu=False, first_gpu=False, frames=None, gpu=0, labels='/home/klinzing/Bunsen-Package_v2.pkg.slp', last_gpu=False, models=['/home/klinzing/201228_122201.single_instance/training_config.json'], only_labeled_frames=False, only_suggested_frames=True, output=None, test_pipeline=False, video_path='', **{'bottomup.batch_size': 4, 'bottomup.peak_threshold': None, 'single.batch_size': 4, 'single.peak_threshold': None, 'topdown.batch_size': 4, 'topdown.peak_threshold': None, 'tracking.clean_instance_count': None, 'tracking.clean_iou_threshold': None, 'tracking.img_scale': None, 'tracking.kf_init_frame_count': None, 'tracking.kf_node_indices': None, 'tracking.match': None, 'tracking.min_match_points': None, 'tracking.min_new_track_points': None, 'tracking.of_max_levels': None, 'tracking.of_window_size': None, 'tracking.post_connect_single_breaks': None, 'tracking.pre_cull_iou_threshold': None, 'tracking.pre_cull_to_target': None, 'tracking.similarity': None, 'tracking.target_instance_count': None, 'tracking.track_window': None, 'tracking.tracker': 'none', 'video.dataset': '', 'video.input_format': ''})
System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True
Traceback (most recent call last):
  File "/home/klinzing/.conda/envs/sleap_alpha/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/inference.py", line 2922, in main
    model_paths_by_head, labels_path=args.labels, policy_args=policy_args
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/inference.py", line 2780, in make_predictor_from_models
    **kwargs,
TypeError: from_trained_models() got an unexpected keyword argument 'confmap_model_path'
```

**Comment by talmo** [comment]
Alright, sorry about that @jens-k! I neglected to add some tests for single instance models and that caused a whole series of problems 🤦

Tests and fixes added now and should be good to go by just updating from the same branch again:
```
pip install --upgrade https://github.com/murthylab/sleap/archive/talmo/inference_cli.zip
```

Let me know if there's any new issues with this patch!

**Comment by jens-k** [comment]
Mmh, its downloaded and installed but didnt change anything (also not with --no-cache-dir).

**Comment by talmo** [comment]
Hey @jens-k,

Alright, I put out a new pre-release that includes these fixes and tested it -- give it a go:
```
conda env remove -n sleap_alpha
conda create -n sleap_alpha -c sleap/label/dev sleap=1.1.0a9
```
Let me know if you get any of the same errors.

This has been a stubborn set of bugs... Thanks for the patience!

**Comment by jens-k** [comment]
Hey @talmo ,
unfortunately it still fails:
```
Traceback (most recent call last):
  File "/home/klinzing/.conda/envs/sleap_alpha/bin/sleap-track", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.1.0a9', 'console_scripts', 'sleap-track')())
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/inference.py", line 2966, in main
    video_predicted_frames = predictor.predict(video_reader).labeled_frames
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/inference.py", line 1064, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/inference.py", line 1007, in _make_labeled_frames_from_generator
    for ex in generator:
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/inference.py", line 968, in _predict_generator
    for ex in self.pipeline.make_dataset():
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/data/pipelines.py", line 274, in make_dataset
    ds = self.providers[0].make_dataset()
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/nn/data/providers.py", line 288, in make_dataset
    test_image = tf.convert_to_tensor(self.video.get_frame(self.video.last_frame_idx))
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/io/video.py", line 1011, in get_frame
    return self.backend.get_frame(idx)
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/sleap/io/video.py", line 319, in get_frame
    frame = self.__dataset_h5[idx]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/h5py/_hl/selections.py", line 466, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/home/klinzing/.conda/envs/sleap_alpha/lib/python3.6/site-packages/h5py/_hl/selections.py", line 486, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (-1) out of range (0--1)
```

I wish I could help more than by just posting my errors here. Python is still a bit obscure to me though. If there's something I can do please let me know.

**Comment by talmo** [comment]
Argh! Thought we had it 😢

Okay, on to the next step.

From the error it seems like SLEAP isn't able to load the frames that it needs to run inference on. I'm assuming these are the suggested frames, right?

This might have been an issue from a past version where suggested frames weren't getting exported correctly together with the labeled ones. Try re-exporting your dataset from the new version from this menu option: **Predict** -> **Export Training Package**:
![image](https://user-images.githubusercontent.com/3187454/104869023-c3cc9e00-58f9-11eb-9ce6-01d1b9d17341.png)

Then try running the inference using the newly generated .pkg.slp file.

If you get a different error, let me know, but either way if it doesn't work, do you mind dropping the .pkg.slp file on Google Drive and sending it over? You can email it to `talmo@princeton.edu` if you prefer not to post the link here.

We'll get this solved yet!!

**Comment by jens-k** [comment]
Ok, so now it runs through and produces an output. However, when I merge the output to my project, it shows me all the 500 suggested frames but each show "0/1 merged instance". It shows the package name under 'video'. Not sure if that's expected (it used to show me the video filename and ask me for its location).

![image](https://user-images.githubusercontent.com/10050167/104871016-f7b6bc00-5917-11eb-87a9-e6beed851e10.png)

**Comment by talmo** [comment]
Hey @jens-k,

Just a quickie update: Yup, this is definitely an issue. The videos should get merged into the existing ones when merging back in. I'm working on fixing that and will update you when it's ready.

PS: Thanks for all the bug reports Jens!! You're catching a lot that we missed, so I really appreciate it :)

**Comment by jens-k** [comment]
Ok nice, that seems to have worked!

I could import the results of the package-based training. It showed me the correct video location for each frame **but also showed me "0/1 merged instances merged" in every case**. Not sure if that is intended behavior, the instances were all there in the end and it seems to be fine. 

I'll correct the predicted frames now, train again, and see if everything goes smoothly now. 
I'll close the issue for now and will re-open if necessary.

Thanks for your help!!
