### ISSUE TITLE
Export training package memory error

### ISSUE THREAD

**Issue by nachonacho2** [murthylab/sleap#461]
Hi @talmo,
I've just updated my local SLEAP install to v1.1.0a9 and ran into a memory error (copied below) when exporting a training package with 701 labelled frames. I tested a few previous versions and the same error is encountered in versions 1.1.0a8 , 1.1.0a7, and 1.0.10. The resulting file is 1.44 GB.
Using v1.0.9, the export completes without error and produces a 792 MB file that seems to train appropriately using v1.1.0a9 in colab.
My local machine is running Windows 10 on an i7-8565U with 16 GB RAM.

```
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\gui\commands.py", line 301, in exportTrainingPackage
    self.execute(ExportTrainingPackage)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\gui\commands.py", line 233, in execute
    command().execute(context=self, params=kwargs)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\gui\commands.py", line 130, in execute
    self.do_with_signal(context, params)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\gui\commands.py", line 154, in do_with_signal
    cls.do_action(context, params)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\gui\commands.py", line 1018, in do_action
    suggested=cls.suggested,
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\io\dataset.py", line 1608, in save_file
    write(filename, labels, *args, **kwargs)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\io\format\main.py", line 158, in write
    return disp.write(filename, source_object, *args, **kwargs)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\io\format\dispatch.py", line 78, in write
    return adaptor.write(filename, source_object, *args, **kwargs)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\io\format\hdf5.py", line 247, in write
    suggested=suggested,
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\io\dataset.py", line 1792, in save_frame_data_hdf5
    frame_numbers=frame_nums,
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\io\video.py", line 1335, in to_hdf5
    frame_data = self.get_frames(frame_numbers)
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\sleap\io\video.py", line 1024, in get_frames
    return np.stack([self.get_frame(idx) for idx in idxs], axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "C:\Users\user\Anaconda3\envs\sleap_alpha\lib\site-packages\numpy\core\shape_base.py", line 433, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
  File "<__array_function__ internals>", line 6, in concatenate
MemoryError: Unable to allocate 29.1 GiB for an array with shape (8259, 972, 1296, 3) and data type uint8

```

**Comment by talmo** [comment]
Hi @nachonacho2,

Thanks for testing this in different versions!

Are you exporting these with suggestions? That is, do you export by going to **Predict** -> **Export Training Package**?
![image](https://user-images.githubusercontent.com/3187454/104869023-c3cc9e00-58f9-11eb-9ce6-01d1b9d17341.png)

Do you get the same error if you export with **Predict** -> **Export User Labels Only**?

Thanks!

Talmo

**Comment by nachonacho2** [comment]
Thanks for the quick reply @talmo.

Yes, I was exporting via the "Export Training Package" menu option. I'm able to successfully export in v1.1.0a9 with the "Export User Labels Only" option with no error and it produces a file of the same size as produced by v1.0.9.

In the "labelling suggestions'" window, > 17,000 are listed; I guess the change in behaviour with the new version is that these suggestions weren't exported previously? After "clearing" these suggestions (generating only 1 suggestion per video), the "Export Training Package" option completes as expected. It might be good have an explicit "clear suggestions" button and/or maybe only one "Export Package" menu option that opens a secondary window with options for the user to select what is exported.
Anyhow, mystery resolved - largely user misunderstanding/error :)

Thanks!
