### ISSUE TITLE
Error when importing maDLC data to SLEAP project

### ISSUE THREAD

**Issue by Xiaoyu-Tong** [murthylab/sleap#515]
Hi,

I was trying to import a maDLC csv file (a maDLC csv file for a single video with name CollectedData_MyName.csv) to  SLEAP project using the GUI (File -> Import -> Deeplabcut dataset). After clicking, the GUI did not change anything nor give me a message, and I got the following error in the Anaconda prompt:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 268, in importDLC
    self.execute(ImportDeepLabCut)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 236, in execute
    command().execute(context=self, params=kwargs)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 133, in execute
    self.do_with_signal(context, params)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 157, in do_with_signal
    cls.do_action(context, params)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 713, in do_action
    labels = Labels.load_deeplabcut(filename=params["filename"])
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\dataset.py", line 1860, in load_deeplabcut
    return read(filename, for_object="labels", as_format="deeplabcut")
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\format\main.py", line 99, in read
    return disp.read(filename, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\format\dispatch.py", line 56, in read
    return adaptor.read(file, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\format\deeplabcut.py", line 78, in read
    file=file, full_video=full_video, *args, **kwargs
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\format\deeplabcut.py", line 178, in read_frames
    data[(animal_name, node, "x")][i],
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\pandas\core\frame.py", line 2905, in __getitem__
    return self._getitem_multilevel(key)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\pandas\core\frame.py", line 2955, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\pandas\core\indexes\multi.py", line 2714, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 713, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 711, in pandas._libs.hashtable.UInt64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 718, in pandas._libs.hashtable.UInt64HashTable.get_item
KeyError: 86

Could you please help me solve this issue? Thank you very much!

Xiaoyu

**Comment by Xiaoyu-Tong** [comment]
I am using the lastest version of SLEAP

**Comment by ariematsliah-princeton** [comment]
Hi @Xiaoyu-Tong 
Can you please email your csv file to sleap@princeton.edu? We'll try to reproduce the error and advise on solution.

Thanks

**Comment by Xiaoyu-Tong** [comment]
Hi @ariematsliah-princeton,

Thank you for the reply and I have sent the csv file to the above email address.

Xiaoyu

**Comment by ariematsliah-princeton** [comment]
Thanks for sending the csv file.
I believe the issue is that not all "individuals" have the same body parts.
Specifically, in this dataset there are 3 individuals:
"individual2", "individual2" and "single"

While the first two share the same body parts, "single" has only one: "Implant"

Currently we cannot import such datasets - consider removing "single" and try again.

**Comment by Xiaoyu-Tong** [comment]
> Thanks for sending the csv file.
> I believe the issue is that not all "individuals" have the same body parts.
> Specifically, in this dataset there are 3 individuals:
> "individual1", "individual2" and "single"
> 
> While the first two share the same body parts, "single" has only one: "Implant"
> 
> Currently we cannot import such datasets - consider removing "single" and try again.

Hi,

Thank you for the answer. I can now import DLC files! But is it normal that whenever I import a file it generates a new SLEAP project for me?

**Comment by ariematsliah-princeton** [comment]
This is the expected behavior right now. You can also import multiple DLC files at once from a folder and then it'll create a single project.

**Comment by Xiaoyu-Tong** [comment]
> This is the expected behavior right now. You can also import multiple DLC files at once from a folder and then it'll create a single project.

I see, thanks. Just one more question. How could I import DLC labeled data to an existing project so that the project contains both the data labeled in SLEAP and the data imported from DLC? Thank you!

**Comment by ariematsliah-princeton** [comment]
Can you try saving the projects separately first, then open once of them and use the "File -> Merge into Project..." option. Hope it works :)

**Comment by Xiaoyu-Tong** [comment]
OK Thanks! Will try that.

**Comment by Xiaoyu-Tong** [comment]
Hi @ariematsliah-princeton,

I think overall it works. Thank you! But do you have any idea how should I merge them if two videos (projects) have images with the same names (i.e. frame001, frame002, etc.)?

**Comment by ariematsliah-princeton** [comment]
Not sure if we have a built in solution to this case, but it should be easy to rename frames in the csv files before you import them?

**Comment by Xiaoyu-Tong** [comment]
OK. Thank you for all the help!
