### ISSUE TITLE
Install error (typo?) in supervised_id branch

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#543]
Hello
I was trying to install the supervised_id branch and there's a weird bug, most likely a typo, but not clear.
Thanks

```
(sleap) cat@cat-Precision-T3610:~$ pip install git+https://github.com/murthylab/sleap.git@talmo/supervised_id
Collecting git+https://github.com/murthylab/sleap.git@talmo/supervised_id
  Cloning https://github.com/murthylab/sleap.git (to talmo/supervised_id) to /tmp/pip-FXgPKT-build
    Complete output from command python setup.py egg_info:
    /tmp/easy_install-DQRsrI/setuptools_scm-6.0.1/src
    <pkg_resources.WorkingSet object at 0x7fba83d34350>
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-FXgPKT-build/setup.py", line 62, in <module>
        python_requires=">=3.6",
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-DQRsrI/setuptools_scm-6.0.1/setup.py", line 52, in <module>
        entry_points={
      File "/tmp/easy_install-DQRsrI/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
        setup(
      File "/tmp/easy_install-DQRsrI/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
      File "/tmp/easy_install-DQRsrI/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-DQRsrI/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-FXgPKT-build/
(sleap) cat@cat-Precision-T3610:~$ 
```

**Comment by talmo** [comment]
Hey @catubc,

Looks like this might be using the system python (2.7) instead of the environment's, judging by the paths on the error log:
```
      File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
```

Try `which pip` to check and maybe `conda install pip` to get it in the current conda environment.

Cheers,

Talmo

**Comment by catubc** [comment]
Oh yes, you are right. Sorry I reinstalled conda and didn't notice.
Thanks!
