### ISSUE TITLE
Enable to export training package -- "ValueError: all input arrays must have the same shape", but videos do have same dimensions

### ISSUE THREAD

**Issue by Xiaoyu-Tong** [murthylab/sleap#545]
Hi,

When I was trying to export training package from my SLEAP project, it gave me the error attached below. The videos do have same height, width and number of channels. So I have no idea where the error comes from. For your reference, I am sending the erroneous project file to sleap@princeton.edu. Thank you for your help in advance!

Xiaoyu

The error messages:

 Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 304, in exportTrainingPackage
    self.execute(ExportTrainingPackage)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 236, in execute
    command().execute(context=self, params=kwargs)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 133, in execute
    self.do_with_signal(context, params)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 157, in do_with_signal
    cls.do_action(context, params)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 1102, in do_action
    suggested=cls.suggested,
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\gui\commands.py", line 1079, in export_dataset_gui
    progress_callback=update_progress,
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\dataset.py", line 1765, in save_file
    write(filename, labels, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\format\main.py", line 158, in write
    return disp.write(filename, source_object, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\format\dispatch.py", line 78, in write
    return adaptor.write(filename, source_object, *args, **kwargs)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\format\hdf5.py", line 249, in write
    progress_callback=progress_callback,
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\dataset.py", line 2002, in save_frame_data_hdf5
    frame_numbers=frame_nums,
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\video.py", line 1342, in to_hdf5
    frame_data = self.get_frames(frame_numbers)
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\sleap\io\video.py", line 1030, in get_frames
    return np.stack([self.get_frame(idx) for idx in idxs], axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "c:\programdata\anaconda3\envs\sleap_env\lib\site-packages\numpy\core\shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by Xiaoyu-Tong** [comment]
Update:

I did a little investigation and realized that the number of labeled frames are also inconsistent. In the GUI, it shows there are 874 labeled frames in total, which is the correct number; however, when I use Labels.load_file to examine the project in the backend, it shows: Labels(labeled_frames=15312, videos=10, skeletons=1, tracks=347). The number of labeled frames is far from correct. Then I tried to further examine what are those "labeled frames", and found that many of the "false positive" labeled frames have zero instance. This kind of makes sense because I did not label them at all. However I am not sure if they are in the final training set. And if they are, it seems to be a fatal error to me because those frames with zero instance do have instances, just that I didn't label. Because the GUI can get the number of labeled frames correctly, I doubt that the backend is reading from a wrong source.

Thanks,
Xiaoyu

**Comment by talmo** [comment]
Hi @Xiaoyu-Tong,

Right, so several layers here.

First, it'd be good to find out where those extra labeled frames are coming from. (Probably inference/merging?)

Second, the training *should* filter the labels to the appropriate subset like the GUI counter, but I'm guessing this is failing in this case.

Try re-saving the original labels like this:
```
In [1]: import sleap

In [2]: labels = sleap.load_file("2BMv4_NoImplant.slp")

In [3]: labels
Out[3]: Labels(labeled_frames=15312, videos=10, skeletons=1, tracks=347)

In [4]: labels.remove_empty_frames()

In [5]: labels
Out[5]: Labels(labeled_frames=874, videos=10, skeletons=1, tracks=347)
```

Here's a self-contained snippet:
```py
import sleap
labels = sleap.load_file("2BMv4_NoImplant.slp")
labels.remove_empty_frames()
labels.save("2BMv4_NoImplant.no_empty.slp")
```

Sent you the output of that over email.

Let me know if you still get the same error!

Talmo

**Comment by Xiaoyu-Tong** [comment]
Hi @talmo ,

Thanks for the update. But unfortunately the same error persists...

**Comment by talmo** [comment]
Oh I see, my bad, from the error it looks like it's happening when you try to export the training package? Could you just confirm that for when we track down the bug?

In the meantime, you could try removing the videos with incompatible shapes or try creating a new project with homogenous inputs (preferably not imported from DLC since those are a little harder to work with).

We're going to be a little delayed with responses this and next week but we'll check it out as soon as we get a chance. Thanks!

**Comment by Xiaoyu-Tong** [comment]
Hi @talmo ,

As I mentioned in the original post of this issue, I got this error when trying to export the training package on local disk. And it was indeed when I added some more labels from DLC project... I have no issue using SLEAP from sketch project. And errors just happened when DLC is involved.

**Comment by talmo** [comment]
Hi @Xiaoyu-Tong,

Are you still having this issue?

If so, do you want to give it a go in [SLEAP v1.1.5](https://github.com/murthylab/sleap/releases/tag/v1.1.5)?

**Comment by talmo** [comment]
Closing this issue due to inactivity but please feel free to comment again if you're still having issues and we'll reopen it.
