### ISSUE TITLE
Tensorflow Colab Notebooks

### ISSUE THREAD

**Issue by mparteagaa** [murthylab/sleap#558]
I labelled frames locally with SLEAP. I exported the whole package to work on Google Colab. Now when I attempt to run the section **Train a model** I am getting the following error:   

  
```
Epoch 1/200
2021-06-15 09:47:28.992751: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-06-15 09:47:30.419494: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
WARNING:tensorflow:Callbacks method "on_train_batch_end" is slow compared to the batch time (batch time: 0.0203s vs "on_train_batch_end" time: 0.2511s). Check your callbacks.
Traceback (most recent call last):
  File "/usr/local/bin/sleap-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 1582, in main
    trainer.train()
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 892, in train
    verbose=2,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/callbacks.py", line 280, in on_epoch_end
    figure = self.plot_fn()
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 1061, in <lambda>
    viz_fn=lambda: visualize_example(next(training_viz_ds_iter)),
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 1042, in visualize_example
    preds = inference_layer(tf.expand_dims(img, axis=0))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 1006, in call
    preds = self.keras_model(imgs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 386, in call
    inputs, training=training, mask=mask)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/functional.py", line 508, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/merge.py", line 183, in call
    return self._merge_function(inputs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/layers/merge.py", line 522, in _merge_function
    return K.concatenate(inputs, axis=self.axis)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py", line 2881, in concatenate
    return array_ops.concat([to_dense(x) for x in tensors], axis)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1654, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1207, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,69,90,162] vs. shape[1] = [1,70,90,243] [Op:ConcatV2] name: concat
```  

`
  Comparing another code that was working a few days ago, I see that the **Validation** value was lower (I also had less frames labelled). 
  
  `INFO:sleap.nn.training:  Splits: Training = 42 / Validation = 5.`

I don't know if that has anything to do.  I also check all the videos and they are the same dimensions. I dont know what could be the issue here. I also tried to google the error but I dont seem to understand where the dimensions for concatenation are not matching.

 Any clue where this error is coming from?

**Comment by talmo** [comment]
Hi @mparteagaa,

Glad you caught that. Yeah, the input scaling is something you just want to adjust down when you have images that are too large. Making them larger doesn't add information, so it doesn't really help to have an input scaling > 1.0.

Since you got it working, I'll go ahead and close this issue but feel free to comment or open another one if you're still having problems.

Cheers,

Talmo
