### ISSUE TITLE
KeyError: 'instances'

### ISSUE THREAD

**Issue by jiespino1** [murthylab/sleap#567]
I am getting the following error when trying to predict and track instances in my uploaded video while using the centroid model, I double checked all of my files and everything seems to be correct on my end. 

```
2021-06-30 21:29:20.860562: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Started inference at: 2021-06-30 21:29:22.331389
Args:
  data_path: 2021-06-25_13-41-25-1.mp4
  models: ['picamera_test.centroid']
  frames: None
  only_labeled_frames: False
  only_suggested_frames: False
  output: None
  no_empty_frames: False
  verbosity: rich
  video.dataset: None
  video.input_format: channels_last
  cpu: False
  first_gpu: False
  last_gpu: False
  gpu: 0
  peak_threshold: 0.2
  batch_size: 4
  open_in_gui: False
  tracking.tracker: simple
  tracking.target_instance_count: None
  tracking.pre_cull_to_target: None
  tracking.pre_cull_iou_threshold: None
  tracking.post_connect_single_breaks: None
  tracking.clean_instance_count: None
  tracking.clean_iou_threshold: None
  tracking.similarity: None
  tracking.match: None
  tracking.track_window: None
  tracking.min_new_track_points: None
  tracking.min_match_points: None
  tracking.img_scale: None
  tracking.of_window_size: None
  tracking.of_max_levels: None
  tracking.kf_node_indices: None
  tracking.kf_init_frame_count: None
2021-06-30 21:29:22.333836: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-06-30 21:29:22.362381: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:22.362969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-06-30 21:29:22.363030: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-06-30 21:29:22.364774: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-06-30 21:29:22.366735: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-06-30 21:29:22.367106: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-06-30 21:29:22.369199: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-06-30 21:29:22.370188: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-06-30 21:29:22.374885: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-06-30 21:29:22.375018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:22.375632: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:22.376168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
Versions:
SLEAP: 1.1.4
TensorFlow: 2.3.1
Numpy: 1.18.5
Python: 3.7.10
OS: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic

System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True

Video: 2021-06-25_13-41-25-1.mp4
2021-06-30 21:29:22.439292: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-30 21:29:22.444422: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2199995000 Hz
2021-06-30 21:29:22.444617: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5559ec003100 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-30 21:29:22.444645: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-06-30 21:29:22.643280: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:22.644086: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5559ec0032c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-06-30 21:29:22.644122: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2021-06-30 21:29:22.644360: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:22.644896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2021-06-30 21:29:22.644980: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-06-30 21:29:22.645026: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-06-30 21:29:22.645075: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-06-30 21:29:22.645107: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-06-30 21:29:22.645141: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-06-30 21:29:22.645166: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-06-30 21:29:22.645193: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-06-30 21:29:22.645285: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:22.645868: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:22.646395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2021-06-30 21:29:22.646477: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-06-30 21:29:23.144969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-30 21:29:23.145033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2021-06-30 21:29:23.145061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2021-06-30 21:29:23.145302: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:23.146018: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-06-30 21:29:23.146631: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13970 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
Predicting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ETA: -:--:-- ?
Traceback (most recent call last):
  File "/usr/local/bin/sleap-track", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 3040, in main
    labels_pr = predictor.predict(provider)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 390, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 2010, in _make_labeled_frames_from_generator
    for ex in generator:
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 300, in _predict_generator
    ex = process_batch(ex)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 266, in process_batch
    preds = self.inference_model.predict_on_batch(ex)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1788, in predict_on_batch
    outputs = predict_function(iterator)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in user code:

    /usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1462 predict_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py:1749 call  *
        peaks_output = self.instance_peaks(example, crop_output)
    /usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py:646 call  *
        a = tf.expand_dims(

    KeyError: 'instances'
```

**Comment by talmo** [comment]
Hi @jiespino1,

It looks like you're trying to do inference using just a centroid model. For the top-down approach, you need to train the two stages separately (centroid and centered instance models) and provide both to `sleap-track`.

There's a little example here: https://sleap.ai/notebooks/Training_and_inference_using_Google_Drive.html#inference-with-top-down-models

Let me know if you have any questions!

Cheers,

Talmo

**Comment by jiespino1** [comment]
Hello @talmo,

Thank you for the response, that seems to have solved the issue.

Best,

Jorge
