### ISSUE TITLE
Unable to Complete Centroid training due to 'RaggedTensor' Issue

### ISSUE THREAD

**Issue by msakarvadia** [murthylab/sleap#585]
Hi Murthylab,

I have been trying to train a top down model, but I have been unable to complete training the first centroid model. I have tried training with several different skeletons, but I can't seem to train even a really simple skeleton without running into an error repeatedly (pasted below).

I am attaching my training job package. 

I initially suspected it could have been empty skeleton instances, but I have checked multiple times and I believe that all of my labeled frame have correct skeletons.

I also was wondering if it could be at all related to: https://github.com/tensorflow/tensorflow/issues/37351 (but it seems that other people have been able to successfully use SLEAP with the default version of tensorflow in the conda environment.

I would really appreciate any help debugging this issues.

Thanks,
Mansi

[180904_A_F1_GP014251_Trim.slp.training_job.zip](https://github.com/murthylab/sleap/files/7165868/180904_A_F1_GP014251_Trim.slp.training_job.zip)
 

```
INFO:sleap.nn.training:Starting training loop...
Epoch 1/2
2021-09-14 23:51:59.332997: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-09-14 23:52:03.548324: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.1519s vs `on_train_batch_end` time: 0.3174s). Check your callbacks.
200/200 - 171s - loss: 3.0702e-04 - val_loss: 3.0124e-04
Epoch 2/2
200/200 - 170s - loss: 2.9891e-04 - val_loss: 2.9533e-04
INFO:sleap.nn.training:Finished training loop. [5.9 min]
INFO:sleap.nn.training:Deleting visualization directory: 210914_194356.centroid/viz
INFO:sleap.nn.training:Saving evaluation metrics to model folder...
Predicting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ETA: -:--:-- ?
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1296, in truediv
    return _truediv_python3(x, y, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1221, in _truediv_python3
    x = ops.convert_to_tensor(x, name="x")
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: TypeError: object of type 'RaggedTensor' has no len()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sleap-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 1617, in main
    trainer.train()
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 904, in train
    self.evaluate()
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/training.py", line 917, in evaluate
    split_name="train",
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/evals.py", line 699, in evaluate_model
    labels_pr = predictor.predict(labels_reader, make_labels=True)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 390, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 2011, in _make_labeled_frames_from_generator
    for ex in generator:
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 300, in _predict_generator
    ex = process_batch(ex)
  File "/usr/local/lib/python3.7/dist-packages/sleap/nn/inference.py", line 279, in process_batch
    np.expand_dims(ex["scale"], axis=1), axis=1
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 205, in wrapper
    result = dispatch(wrapper, args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 118, in dispatch
    result = dispatcher.handle(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/ragged/ragged_dispatch.py", line 219, in handle
    ragged_tensor_shape.RaggedTensorDynamicShape.from_tensor(y))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/ragged/ragged_tensor_shape.py", line 470, in broadcast_dynamic_shape
    shape_x = shape_x.broadcast_dimension(axis, shape_y.dimension_size(axis))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/ragged/ragged_tensor_shape.py", line 351, in broadcast_dimension
    condition, data=broadcast_err, summarize=10)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 158, in Assert
    (condition, "\n".join(data_str)))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'Unable to broadcast: dimension size mismatch in dimension'
0
b'lengths='
4
b'dim_size='
0
```

**Comment by talmo** [comment]
Hi @msakarvadia,

Hmm, this looks pretty strange, especially considering that training seems to go through a couple of epochs okay.

I'll have a look at your training package to see what might be going on, but I suspect that this might just be a strange artifact of a bad model resulting in weird predictions.

What version of TensorFlow are you using?

Cheers,

Talmo

**Comment by msakarvadia** [comment]
Hi @talmo,

I am using TensorFlow version 2.3.1 in my conda environment.

Thank you for your help!

-Mansi

**Comment by talmo** [comment]
Hi @msakarvadia,

First of all, very cool data!

I had a chance to play around with your training package last week and seem to be getting reasonable results. Part of the challenge is that you have a pretty large variability in scale the animal. I adjusted the network configuration slightly to deal with this, but I also added an additional keypoint on the tail. The idea is that it helps to define the bounding box of the animal to improve rotational symmetry. Check it out (this is a prediction):

![image](https://user-images.githubusercontent.com/3187454/134047848-ae2212c9-1ac1-4000-880c-77a002f460c4.png)

![image](https://user-images.githubusercontent.com/3187454/134047883-e98e7544-911b-4ecc-97f6-236a94ed8b3f.png)


Here's the training configurations: [configs.zip](https://github.com/murthylab/sleap/files/7197602/configs.zip)

You should be able to use those anyway, but I'd recommend adding the tail keypoint.

Give it a go and/or let me know if you have any questions!

Cheers,

Talmo

**Comment by msakarvadia** [comment]
Hi @talmo,

Thank you for your response!

I did try and use the exact configuration files that you provided for a model with 3 points (as you suggested) for the skeleton, but I ran into the exact same "RaggedTensor" error. 

I also tried to train a model on a dataset where I had specified a more biologically relevant (and detailed) skeleton which would have provided a nice bounding box for the animal with your configuration files, and I ran into the exact same error once again. 

I have been able to successfully train and predict poses on an example fruit fly dataset provided in your documentation, so I don't think this is a software issue, but most likely related to my data and model.

Could I email you the training package for you to take a look at, since there is a 25 MB limit to attachments on GitHub?


Thanks,
Mansi

**Comment by talmo** [comment]
Hi @msakarvadia,

Very sorry about the delay -- I'm currently traveling.

Did you get a chance to figure out the problem? If not, feel free to shoot that package to `sleap@princeton.edu` or upload it to Google Drive/Dropbox/etc and send a link and we'll review ASAP.

Thanks!

Talmo

**Comment by msakarvadia** [comment]
Thanks @talmo! I just sent the file via email.

**Comment by talmo** [comment]
Closing this issue due to inactivity but please feel free to comment again if you're still having issues and we'll reopen it. Sorry about letting it slip through the cracks! If you didn't manage to find a workable solution we're happy to help out again -- please feel free to reach out.
