### ISSUE TITLE
Getting error while installing Sleaap

### ISSUE THREAD

**Issue by Sushen2021** [murthylab/sleap#597]
Hi, I have installed sleap via Anaconda prompt as instructed in sleap.ai site. After successful installation when I try to open Sleap label GUI it gives following error --
(base) C:\Users\User>conda activate sleap

(sleap) C:\Users\User>sleap-label
Traceback (most recent call last):
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Users\User\anaconda3\envs\sleap\Scripts\sleap-label-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.1.5', 'console_scripts', 'sleap-label')())
  File "d:\Users\User\anaconda3\envs\sleap\Scripts\sleap-label-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\importlib_metadata\__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "d:\Users\User\anaconda3\envs\sleap\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\sleap\__init__.py", line 13, in <module>
    import sleap.nn
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\sleap\nn\__init__.py", line 1, in <module>
    import sleap.nn.architectures
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\sleap\nn\architectures\__init__.py", line 1, in <module>
    from sleap.nn.architectures import leap
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\sleap\nn\architectures\leap.py", line 10, in <module>
    from sleap.nn.architectures import encoder_decoder
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\sleap\nn\architectures\encoder_decoder.py", line 29, in <module>
    import tensorflow as tf
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "d:\Users\User\anaconda3\envs\sleap\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

I used older version of sleap in this pc earlier without any issue. And then for some reason I had uninstalled that. Now during reinstalling the sleap 1.1.5 I am getting That error. 
I need

**Comment by talmo** [comment]
Closing this issue due to inactivity but please feel free to comment again if you're still having issues and we'll reopen it.
