### ISSUE TITLE
RuntimeError: Unable to get link info (addr overflow, addr = 11104, size = 176, eoa = 2048)

### ISSUE THREAD

**Issue by catubc** [murthylab/sleap#610]
Hello

We are trying to load an .slp file to label some data (v19), but get the crash below.  v18 seems to load fine. 
Is there any insight into this bug?  Did sleap crash during saving v19?

Thanks so much!

```
(sleap) cat@cat-ThinkPad-T520:~$ sleap-label
2021-11-26 01:56:39.925287: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Saving config: /home/cat/.sleap/1.1.5/preferences.yaml
/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/shiboken2/files.dir/shibokensupport/signature/parser.py:97: FutureWarning: split() requires a non-empty pattern match.
  return [x.strip() for x in split(argstr) if x.strip() not in ("", ",")]
Restoring GUI state...
2021-11-26 01:56:43.080738: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-11-26 01:56:43.110055: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-26 01:56:43.110494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.8475GHz coreCount: 20 deviceMemorySize: 7.93GiB deviceMemoryBandwidth: 298.32GiB/s
2021-11-26 01:56:43.110560: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-11-26 01:56:43.112828: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-11-26 01:56:43.114235: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-11-26 01:56:43.114657: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-11-26 01:56:43.116761: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-11-26 01:56:43.118350: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-11-26 01:56:43.123118: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-11-26 01:56:43.123480: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-26 01:56:43.123946: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-11-26 01:56:43.124222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0

Software versions:
SLEAP: 1.1.5
TensorFlow: 2.3.1
Numpy: 1.18.5
Python: 3.6.13
OS: Linux-4.15.0-162-generic-x86_64-with-debian-buster-sid

Happy SLEAPing! :)
Traceback (most recent call last):
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/gui/commands.py", line 256, in openProject
    self.execute(OpenProject, first_open=first_open)
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/gui/commands.py", line 236, in execute
    command().execute(context=self, params=kwargs)
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/gui/commands.py", line 133, in execute
    self.do_with_signal(context, params)
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/gui/commands.py", line 157, in do_with_signal
    cls.do_action(context, params)
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/gui/commands.py", line 578, in do_action
    context.app.loadProjectFile(filename)
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/gui/app.py", line 1351, in loadProjectFile
    labels = Labels.load_file(filename, video_search=gui_video_callback)
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/io/dataset.py", line 1814, in load_file
    filename, for_object="labels", video_search=video_search, *args, **kwargs
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/io/format/main.py", line 109, in read
    return disp.read(filename, *args, **kwargs)
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/io/format/dispatch.py", line 55, in read
    if adaptor.can_read_file(file):
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/io/format/hdf5.py", line 57, in can_read_file
    if file.format_id is not None and file.format_id >= 2:
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/io/format/filehandle.py", line 106, in format_id
    if "metadata" in self.file:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/cat/anaconda3/envs/sleap/lib/python3.6/site-packages/h5py/_hl/group.py", line 415, in __contains__
    return self._e(name) in self.id
  File "h5py/h5g.pyx", line 461, in h5py.h5g.GroupID.__contains__
  File "h5py/h5g.pyx", line 462, in h5py.h5g.GroupID.__contains__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 531, in h5py.h5g._path_valid
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5l.pyx", line 212, in h5py.h5l.LinkProxy.exists
RuntimeError: Unable to get link info (addr overflow, addr = 11104, size = 176, eoa = 2048)
```

**Comment by talmo** [comment]
Hi @catubc,

I don't think I've seen this error before. Do you mind sharing the specific SLP file you're trying to open that's resulting in this issue?

BTW: did this happen after importing predictions?

**Comment by catubc** [comment]
Sorry, turns out that the .slp file wasn't completely saved as we ran out of space. Or something along those lines.  
Thanks!
