### ISSUE TITLE
Error about receptive field and input scaling: Dimensions of Input should match.

### ISSUE THREAD

**Issue by yilewang** [murthylab/sleap#636]
Hey Everyone!

I got an error when I finished my training and tried to make predictions in all my frames. I tried to replace my video with a different format but I still got the same error... Could you please give me a hint about the problem? Thank you so much! I am also happy to provide more info about my training parameters and labeling details if it is necessary.

Best Regards, 

Yile

```python
Traceback (most recent call last):
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1252, in _after_plot_update
    overlay.add_to_scene(self.state["video"], frame_idx)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\gui\overlays\instance.py", line 49, in add_to_scene
    nodeLabelSize=self.state.get("node label size", 12),
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 438, in addInstance
    instance = QtInstance(instance=instance, player=self, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 1805, in __init__
    self.updateBox()
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 1881, in updateBox
    rect = self.getPointsBoundingRect()
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 1861, in getPointsBoundingRect
    min((point[0] for point in points)), min((point[1] for point in points))
ValueError: min() arg is an empty sequence
```

**Comment by yilewang** [comment]
Hi, 

When I was dealing with the error above, I realized that this error was probably coming from the inconsistent shape between my instance and the receptive field of my model, so I tried to expand my receptive field. I set up input scaling to 0.5 and Max Stride to 64, however, I got another `dimensions of input error` when I ran the training.

I attached a training example and my error message below. Any comment would be appreciated! Thank you!

Best Regards, 

Yile

![image](https://user-images.githubusercontent.com/37648360/151594580-6f81be7b-fa29-4adf-adeb-85e35ed2809c.png)
![image](https://user-images.githubusercontent.com/37648360/151595724-2132089f-3fde-4efc-9ea6-7edeab9d79c7.png)

```python
Traceback (most recent call last):
  File "C:\Users\Wayne\miniconda3\envs\sleap\Scripts\sleap-train-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap==1.1.5', 'console_scripts', 'sleap-train')())
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 1617, in main
    trainer.train()
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 892, in train
    verbose=2,
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\nn\callbacks.py", line 280, in on_epoch_end
    figure = self.plot_fn()
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 1061, in <lambda>
    viz_fn=lambda: visualize_example(next(training_viz_ds_iter)),
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\nn\training.py", line 1042, in visualize_example
    preds = inference_layer(tf.expand_dims(img, axis=0))
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\sleap\nn\inference.py", line 1006, in call
    preds = self.keras_model(imgs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 386, in call
    inputs, training=training, mask=mask)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\engine\functional.py", line 508, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 183, in call
    return self._merge_function(inputs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 522, in _merge_function
    return K.concatenate(inputs, axis=self.axis)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\keras\backend.py", line 2881, in concatenate
    return array_ops.concat([to_dense(x) for x in tensors], axis)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1654, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1207, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\Wayne\miniconda3\envs\sleap\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,6,7,243] vs. shape[1] = [1,6,8,364] [Op:ConcatV2] name: concat
```

**Comment by talmo** [comment]
Hi @yilewang,

The first error you can actually ignore -- that's just a GUI bug, but it doesn't affect anything functionally.

The second one is a bug related to plotting the single instance visualization during training (#604) which will be fixed in the next version of SLEAP. In the meantime, you can try out the pre-release here → https://github.com/murthylab/sleap/releases/tag/v1.2.0a2

Give that a go and let me know if you're still running into problems!

Cheers,

Talmo

**Comment by yilewang** [comment]
> Hi @yilewang,
> 
> The first error you can actually ignore -- that's just a GUI bug, but it doesn't affect anything functionally.
> 
> The second one is a bug related to plotting the single instance visualization during training (#604) which will be fixed in the next version of SLEAP. In the meantime, you can try out the pre-release here → https://github.com/murthylab/sleap/releases/tag/v1.2.0a2
> 
> Give that a go and let me know if you're still running into problems!
> 
> Cheers,
> 
> Talmo

Dear Talmo,

Thanks for your reply! I installed the pre-release version of the SLEAP and now the problem is solved! Thanks so much for your help. I will close this issue with this comment.
