### ISSUE TITLE
Problem with inference running

### ISSUE THREAD

**Issue by carolinejia22** [murthylab/sleap#649]
Hi! 

I am trying to run SLEAP using an initial 20 frames of training data. The training ran smoothly but I started to have an error when it hit the inference portion, testing 20 random frames in the video. 

```
Traceback (most recent call last):
  File "/home/cjia/anaconda3/envs/sleap/bin/sleap-track", line 33, in <module>
Started inference at: 2022-02-11 17:17:59.634645
    sys.exit(load_entry_point('sleap==1.1.5', 'console_scripts', 'sleap-track')())
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 3041, in main
    labels_pr = predictor.predict(provider)
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 390, in predict
    self._make_labeled_frames_from_generator(generator, data)
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 2011, in _make_labeled_frames_from_generator
    for ex in generator:
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/nn/inference.py", line 319, in _predict_generator
    for ex in self.pipeline.make_dataset():
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/pipelines.py", line 277, in make_dataset
    ds = self.providers[0].make_dataset()
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/nn/data/providers.py", line 388, in make_dataset
    self.video.get_frame(self.video.last_frame_idx)
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/io/video.py", line 1022, in get_frame
    return self.backend.get_frame(idx)
  File "/home/cjia/anaconda3/envs/sleap/lib/python3.6/site-packages/sleap/io/video.py", line 478, in get_frame
    raise KeyError(f"Unable to load frame {idx} from {self}.")
KeyError: "Unable to load frame 29522 from MediaVideo(filename='/nadata/snlkt/data/Caroline/1.SocialPain/1.Sensors/eCBsensor/Videos/Fed/PokingVids_fed/Cage5M1-FOMO-poking-fed.mp4', grayscale=False, bgr=True, dataset='', input_format='channels_last')."
Args:
  data_path: /nadata/snlkt/data/Caroline/1.SocialPain/1.Sensors/eCBsensor/Videos/Fed/PokingVids_fed/Cage5M1-FOMO-poking-fed.mp4
  models: ['/nadata/snlkt/data/Caroline/SLEAP/models/220211_170141.centroid.n=21/training_config.json', '/nadata/snlkt/data/Caroline/SLEAP/models/220211_170634.centered_instance.n=21/training_config.json']
  frames: 2171-28384 (20)
  only_labeled_frames: False
  only_suggested_frames: False
  output: /nadata/snlkt/data/Caroline/SLEAP/predictions/Cage5M1-FOMO-poking-fed.mp4.220211_171743.predictions.slp
Process return code: 1
```

Any advice with this problem? Thank you!

**Comment by carolinejia22** [comment]
Great! Thanks so much. I converted it and it worked.
