### ISSUE TITLE
Error running inference in a full-length video

### ISSUE THREAD

**Issue by aereimer** [murthylab/sleap#657]
I'm using SLEAP 1.2.0a5 (rtx 3070) and while running inference in some frames (current frame; suggested frame) works well, I am running into some errors when trying to do it in a full-length videos (~ 10 min. long) . What can it be related to?

        18050,
        18051,
        18052,
        18053,
        18054,
        18055,
        18056,
        18057,
        18058
    ],
    'only_labeled_frames': False,
    'only_suggested_frames': False,
    'output': 'C:/Users/Adriano Reimer/Documents/sleap_alpha/freezing_ufscar\\predictions\\96_01_H_122021100000_crop1.mp4.220218_115237.predictions.slp',
    'no_empty_frames': True,
    'verbosity': 'json',
    'video.dataset': None,
    'video.input_format': 'channels_last',
    'cpu': False,
    'first_gpu': False,
    'last_gpu': False,
    'gpu': 0,
    'max_edge_length_ratio': 0.25,
    'dist_penalty_weight': 1.0,
    'batch_size': 4,
    'open_in_gui': False,
    'peak_threshold': 0.2,
    'tracking.tracker': 'flow',
    'tracking.target_instance_count': None,
    'tracking.pre_cull_to_target': 0,
    'tracking.pre_cull_iou_threshold': 0.8,
    'tracking.post_connect_single_breaks': 0,
    'tracking.clean_instance_count': None,
    'tracking.clean_iou_threshold': None,
    'tracking.similarity': 'instance',
    'tracking.match': 'greedy',
    'tracking.track_window': 5,
    'tracking.min_new_track_points': None,
    'tracking.min_match_points': None,
    'tracking.img_scale': None,
    'tracking.of_window_size': None,
    'tracking.of_max_levels': None,
    'tracking.kf_node_indices': None,
    'tracking.kf_init_frame_count': None
}

Versions:
SLEAP: 1.2.0a5
TensorFlow: 2.7.1
Numpy: 1.21.5
Python: 3.7.11
OS: Windows-10-10.0.19041-SP0

System:
GPUs: 1/1 available
  Device: /physical_device:GPU:0
         Available: True
        Initalized: False
     Memory growth: True

Video: C:/Users/Adriano Reimer/Documents/Freezing_ufscar-adriano-2021-10-30/Freezing_ufscar-adriano-2021-10-30/videos/96_01_H_122021100000_crop1.mp4
2022-02-18 12:12:15.538248: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:690] Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: -40 } dim { size: -41 } dim { size: -42 } dim { size: 1 } } } inputs { dtype: DT_FLOAT shape { dim { size: -5 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -5 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } } device { type: "GPU" vendor: "NVIDIA" model: "NVIDIA GeForce RTX 3070" frequency: 1725 num_cores: 46 environment { key: "architecture" value: "8.6" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 102400 memory_size: 5734203392 bandwidth: 448064000 } outputs { dtype: DT_FLOAT shape { dim { size: -5 } dim { size: -44 } dim { size: -45 } dim { size: 1 } } }
Finished inference at: 2022-02-18 12:12:15.988640
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\sleap_1.2.0a5\Scripts\sleap-track-script.py", line 33, in <module>
    sys.exit(load_entry_point('sleap', 'console_scripts', 'sleap-track')())
  File "c:\users\adriano reimer\documents\sleap-1.2.0a5\sleap-1.2.0a5\sleap\nn\inference.py", line 3155, in main
    labels_pr.save(output_path)
  File "c:\users\adriano reimer\documents\sleap-1.2.0a5\sleap-1.2.0a5\sleap\io\dataset.py", line 1886, in save
    suggested=embed_suggested,
  File "c:\users\adriano reimer\documents\sleap-1.2.0a5\sleap-1.2.0a5\sleap\io\dataset.py", line 1851, in save_file
    write(filename, labels, *args, **kwargs)
  File "c:\users\adriano reimer\documents\sleap-1.2.0a5\sleap-1.2.0a5\sleap\io\format\main.py", line 158, in write
    return disp.write(filename, source_object, *args, **kwargs)
  File "c:\users\adriano reimer\documents\sleap-1.2.0a5\sleap-1.2.0a5\sleap\io\format\dispatch.py", line 78, in write
    return adaptor.write(filename, source_object, *args, **kwargs)
  File "c:\users\adriano reimer\documents\sleap-1.2.0a5\sleap-1.2.0a5\sleap\io\format\hdf5.py", line 335, in write
    meta_group.attrs["json"] = np.string_(json_dumps(d))
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\ProgramData\Anaconda3\envs\sleap_1.2.0a5\lib\site-packages\h5py\_hl\attrs.py", line 103, in __setitem__
    self.create(name, data=value)
  File "C:\ProgramData\Anaconda3\envs\sleap_1.2.0a5\lib\site-packages\h5py\_hl\attrs.py", line 196, in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5a.pyx", line 50, in h5py.h5a.create
RuntimeError: Unable to create attribute (object header message is too large)
Total runtime: 1174.5604927539825 secs
Predicted frames: 18059/18059
Provenance:
{
    'sleap_version': '1.2.0a5',
    'platform': 'Windows-10-10.0.19041-SP0',
    'command': 'C:\\ProgramData\\Anaconda3\\envs\\sleap_1.2.0a5\\Scripts\\sleap-track C:/Users/Adriano Reimer/Documents/Freezing_ufscar-adriano-2021-10-30/Freezing_ufscar-adriano-2021-10-30/videos/96_01_H_122021100000_crop1.mp4 --frames 0,-18058 -m C:/Users/Adriano Reimer/Documents/sleap_alpha/freezing_ufscar\\models\\220218_105755.single_instance.n=862\\training_config.json --tracking.tracker flow --tracking.pre_cull_to_target 0 --tracking.pre_cull_iou_threshold 0.8 --tracking.similarity instance --tracking.match greedy --tracking.track_window 5 --tracking.post_connect_single_breaks 0 -o C:/Users/Adriano Reimer/Documents/sleap_alpha/freezing_ufscar\\predictions\\96_01_H_122021100000_crop1.mp4.220218_115237.predictions.slp --verbosity json --no-empty-frames',
    'data_path': 'C:/Users/Adriano Reimer/Documents/Freezing_ufscar-adriano-2021-10-30/Freezing_ufscar-adriano-2021-10-30/videos/96_01_H_122021100000_crop1.mp4',
    'model_paths': [
        'C:/Users/Adriano Reimer/Documents/sleap_alpha/freezing_ufscar\\models\\220218_105755.single_instance.n=862\\training_config.json'
    ],
    'output_path': 'C:/Users/Adriano Reimer/Documents/sleap_alpha/freezing_ufscar\\predictions\\96_01_H_122021100000_crop1.mp4.220218_115237.predictions.slp',
    'predictor': 'SingleInstancePredictor',
    'total_elapsed': 1174.5604927539825,
    'start_timestamp': '2022-02-18 11:52:41.428148',
    'finish_timestamp': '2022-02-18 12:12:15.988640'
}

Process return code: 1

**Comment by talmo** [comment]
Hi @aereimer,

Strange that that's happening in a video with so few frames, but that's likely due to some metadata being too large to save. This will typically happen for videos that are many millions of frames, not just ~18k.

Do you mind sharing your video (`96_01_H_122021100000_crop1.mp4`) and the model (`220218_105755.single_instance.n=862`) so I can try to reproduce it and figure out what's wrong? You can send them to `talmo@salk.edu` if you prefer.

Thanks!

Talmo

**Comment by talmo** [comment]
Quick update: I reproduced this issue and am working on a fix.

A workaround for now is to downgrade from 1.2.0a5 to 1.2.0a3 or older.

Will update this thread when we have a fix out.

**Comment by talmo** [comment]
Hi @aereimer,

This will be fixed in the next pre-release, but if you'd like to install the latest development version to try it:

```
git clone https://github.com/murthylab/sleap sleap_develop
cd sleap_develop
conda env create -f environment.yml -n sleap_develop
```
