### ISSUE TITLE
everything was working great until this afternoon...

### ISSUE THREAD

**Issue by eringiglio** [murthylab/sleap#661]
I am baffled. As of this afternoon, every time I load SLEAP I get this message:

Saving config: C:\Users\ering/.sleap/1.1.5/preferences.yaml
Traceback (most recent call last): 
File "C:\Users\ering\anaconda3\envs\sleap\Scripts\sleap-label-script.py", line 33, in <module>                      
  sys.exit(load_entry_point('sleap==1.1.5', 'console_scripts', 'sleap-label')())                                        
File "C:\Users\ering\anaconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 1705, in main                         
  window = MainWindow(labels_path=args.labels_path, reset=args.reset)                                                   
File "C:\Users\ering\anaconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 151, in __init__                    
  self._initialize_gui()                                                                                                
File "C:\Users\ering\anaconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 239, in _initialize_gui             
  self._create_video_player()                                                                                           
File "C:\Users\ering\anaconda3\envs\sleap\lib\site-packages\sleap\gui\app.py", line 255, in _create_video_player           
  color_manager=self.color_manager, state=self.state, context=self.commands                                             
File "C:\Users\ering\anaconda3\envs\sleap\lib\site-packages\sleap\gui\widgets\video.py", line 211, in __init__          
  self.shortcuts = Shortcuts()                                                                                          
File "C:\Users\ering\anaconda3\envs\sleap\lib\site-packages\sleap\gui\shortcuts.py", line 65, in __init__               
  self._shortcuts = self._process_shortcut_dict(shortcuts)                                                              
File "C:\Users\ering\anaconda3\envs\sleap\lib\site-packages\sleap\gui\shortcuts.py", line 69, in _process_shortcut_dict                                                                                                                               
  for action in shortcuts.keys():                                                                                     
AttributeError: 'NoneType' object has no attribute 'keys'  

I have deleted the env in which sleap was installed and re-installed several times, I have restarted the machine, I have uninstalled and re-installed Anaconda itself, and I am still getting this error. I am perplexed. Does anyone have any idea what could be causing this and how I can fix it? Everything was working so _well_ until I tried to set up for the day, too!

**Comment by eringiglio** [comment]
Resolved--deleting the user/ering/.sleap folder and all files within seemed to work, for whatever reason. Aaaaaaaaaugh.
