### ISSUE TITLE
importing dlc dataset to sleap

### ISSUE THREAD

**Issue by BotLights** [murthylab/sleap#676]
im trying to test whether my dataset can be imported in sleap for training but got errors when doing so.

when using the gui import:

Traceback (most recent call last):
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 268, in importDLC
    self.execute(ImportDeepLabCut)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 236, in execute
    command().execute(context=self, params=kwargs)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 133, in execute
    self.do_with_signal(context, params)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 157, in do_with_signal
    cls.do_action(context, params)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 717, in do_action
    labels = Labels.load_deeplabcut(filename=params["filename"])
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\dataset.py", line 1937, in load_deeplabcut
    return read(filename, for_object="labels", as_format="deeplabcut")
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\main.py", line 99, in read
    return disp.read(filename, *args, **kwargs)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\dispatch.py", line 56, in read
    return adaptor.read(file, *args, **kwargs)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\deeplabcut.py", line 78, in read
    file=file, full_video=full_video, *args, **kwargs
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\deeplabcut.py", line 178, in read_frames
    data[(animal_name, node, "x")][i],
  File "E:\Anaconda\envs\sleap\lib\site-packages\pandas\core\frame.py", line 2905, in __getitem__
    return self._getitem_multilevel(key)
  File "E:\Anaconda\envs\sleap\lib\site-packages\pandas\core\frame.py", line 2955, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "E:\Anaconda\envs\sleap\lib\site-packages\pandas\core\indexes\multi.py", line 2714, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 713, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 711, in pandas._libs.hashtable.UInt64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 718, in pandas._libs.hashtable.UInt64HashTable.get_item
KeyError: 140

tried importing the config.yaml instead, but same issue:

Traceback (most recent call last):
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 268, in importDLC
    self.execute(ImportDeepLabCut)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 236, in execute
    command().execute(context=self, params=kwargs)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 133, in execute
    self.do_with_signal(context, params)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 157, in do_with_signal
    cls.do_action(context, params)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 717, in do_action
    labels = Labels.load_deeplabcut(filename=params["filename"])
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\dataset.py", line 1937, in load_deeplabcut
    return read(filename, for_object="labels", as_format="deeplabcut")
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\main.py", line 99, in read
    return disp.read(filename, *args, **kwargs)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\dispatch.py", line 56, in read
    return adaptor.read(file, *args, **kwargs)
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\deeplabcut.py", line 299, in read
    file=FileHandle(csv_path), skeleton=skeleton, full_video=video
  File "E:\Anaconda\envs\sleap\lib\site-packages\sleap\io\format\deeplabcut.py", line 165, in read_frames
    f"Unable to determine frame index for image {img_files[i]}"
ValueError: Unable to determine frame index for image labeled-data

here's a copy of the dataset im testing out
[CollectedData_none.csv](https://github.com/murthylab/sleap/files/8259554/CollectedData_none.csv)

**Comment by talmo** [comment]
Hi @BotLights,

Thanks for providing the test data! It looks like DLC updated their labels format.

We've updated our reader to support this and it will be available in the next version of SLEAP. In the meantime, if you'd like to test it yourself and make sure it works on your end, you can try out the experimental branch like this:

1. Download the SLEAP source and 
```
git clone https://github.com/murthylab/sleap && cd sleap && git checkout talmo/update_madlc_import
```
2. Install:
```
conda env create -f environment.yml -n sleap_testing
```

Then just activate the environment with `conda activate sleap_testing` and use it as normal.

Let me know if that works for you!

Cheers,

Talmo

**Comment by BotLights** [comment]
it works! thanks for the update
