### ISSUE TITLE
import DeepLabCut dataset single-animal

### ISSUE THREAD

**Issue by Guillermo-Hidalgo-Gadea** [murthylab/sleap#702]
Hi @talmo, 

I was wondering if your fix #678 is only for labeled frames in maDLC format?
I have a single-animal project in `dlc==2.2.0.6` I am trying to import and get a similar error as in previous issues #428 and #676:

```
(sleap) C:\Users\hidalggc>sleap-label
Saving config: C:\Users\hidalggc/.sleap/1.2.2/preferences.yaml
Restoring GUI state...

Software versions:
SLEAP: 1.2.2
TensorFlow: 2.6.3
Numpy: 1.19.5
Python: 3.7.12
OS: Windows-10-10.0.19041-SP0

Happy SLEAPing! :)
Traceback (most recent call last):
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 270, in importDLC
    self.execute(ImportDeepLabCut)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 236, in execute
    command().execute(context=self, params=kwargs)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 133, in execute
    self.do_with_signal(context, params)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 157, in do_with_signal
    cls.do_action(context, params)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\gui\commands.py", line 728, in do_action
    labels = Labels.load_deeplabcut(filename=params["filename"])
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\io\dataset.py", line 1985, in load_deeplabcut
    return read(filename, for_object="labels", as_format="deeplabcut")
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\io\format\main.py", line 99, in read
    return disp.read(filename, *args, **kwargs)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\io\format\dispatch.py", line 56, in read
    return adaptor.read(file, *args, **kwargs)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\io\format\deeplabcut.py", line 78, in read
    file=file, full_video=full_video, *args, **kwargs
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\sleap\io\format\deeplabcut.py", line 201, in read_frames
    x, y = data[(node, "x")][i], data[(node, "y")][i]
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\pandas\core\frame.py", line 3457, in __getitem__
    return self._getitem_multilevel(key)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\pandas\core\frame.py", line 3508, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "C:\Users\hidalggc\Anaconda3\envs\sleap\lib\site-packages\pandas\core\indexes\multi.py", line 2932, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 725, in pandas._libs.index.BaseMultiIndexCodesEngine.get_loc
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1832, in pandas._libs.hashtable.UInt64HashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1841, in pandas._libs.hashtable.UInt64HashTable.get_item
KeyError: 324
```
here is a subset of the training-dataset: [test_CollectedData_Sarah.csv](https://github.com/murthylab/sleap/files/8444799/test_CollectedData_Sarah.csv)

Thank you in advance, and congratulations on your great documentation it really is above any expectation!

**Comment by talmo** [comment]
Hi @Guillermo-Hidalgo-Gadea,

Thanks for the detailed bug report! I think you're right -- we hadn't run into the new *single* animal DLC file format yet. Thanks for providing the test data and the full error logs!

I'm tagging this as a bug and we'll work on a fix ASAP. We'll update this thread as soon as we have a patch that you can test.

Cheers,

Talmo

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi @talmo, hi  @roomrys,

thanks for the quick reply! I am really looking forward to compare this to DLC with standard ResNet in single-animal case.

In the meantime I used the following lines to transform all `CollectedData.csv` files from DLC to their format before `v2.2.0.6`. 
After that, import > Multiple DeepLabCut datasets from folder worked perfectly!

I also realized that `dlc==2.2.0.6` updates the labeled data format from previous dlc versions but only in their `.h5` files, so that a dataset generated over multiple training iterations with `dlc < 2.2.0.6` will have `.csv` files that are formated differently (see try - except block below).


```
import os
import pandas as pd
import tkinter.filedialog

def scraper(extension):
    """
    This function walks through subdirectories and lists all files with a given extension
    """
    masterdir = tkinter.filedialog.askdirectory(title="Select directory to scrap:")
    filelist= list()

    for (dirpath, dirname, filename) in os.walk(masterdir):
        filelist += [os.path.join(dirpath,file) for file in filename]

    file_list= [video for video in filelist if extension in video]
    print(f'The function scraper() successfully selected {len(file_list)} files.')

    return file_list

def transformer(filelist):
    """
    This function changes the first column of DLC labeled data after the change to Multiindex after v2.2.0.3
    """
    for file in filelist:
        df = pd.read_csv(file, header=[0, 1, 2])
        try:
            # transform multiindex
            df['scorer'] = df[['scorer', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0']].agg('/'.join, axis=1)
            new_df = df.drop(['Unnamed: 1_level_0', 'Unnamed: 2_level_0'], axis=1)
            # save in old format
            new_df.to_csv(file, sep=',', index=False)
            print(f'transformed for:  {file}')
        except:
            print(f'passed for:  {file}')
    return

filelist = scraper('.csv')
transformer(filelist)
```
